name: Build for intellij-cucumber-scala

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: 1.17-custom=tgz+https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-17.0.11-linux-x64-b1312.2.tar.gz
      - name: Compile & Test
        run: sbt test
